Repository De-cal/6-Favorite_Photo-FE, pull requests merged in 2025-05, with the labels that each got.

#1 Feat/card: card 공통 컴포넌트 추가
  package-lock.json
  package.json
  src/app/layout.js
  src/components/common/Card.jsx
Labels: FE, UI

#2 chores:folder structure revise
  src/app/marketplace/buyers/[id]/page.jsx
  src/app/marketplace/sellers/[id]/page.jsx
Labels: Chore

#4 Temp
  README.md
Labels: Chore

#5 feat: Header 레이아웃 UI 구현
  .env.example
  src/app/layout.js
  src/components/common/Header.jsx
  src/components/common/HeaderLayout.jsx
  src/components/common/Layout.jsx
Labels: FE, UI

#7 refactor: 이미지 이름변경
  src/components/common/Header.jsx
Labels: FE, Refactor

#8 feat: 공용 버튼 컴포넌트 추가
  src/app/page.js
  src/components/ui/buttons/ActionButton.jsx
Labels: FE, UI

#9 Feat/photoCard-sell UI
  .github/PULL_REQUEST_TEMPLATE.md
  src/app/marketplace/_components/Dropdown.jsx
  src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
  src/app/marketplace/_components/SellPhotoCardsModal.jsx
  src/app/marketplace/page.jsx
  src/components/common/Card.jsx
Labels: FE, UI

#14 [refactor] ActionButton 공용 컴포넌트 리팩터링
  .github/pull_request_template.md
  src/components/ui/buttons/ActionButton.jsx
Labels: FE, UI

#13 Feat/market place mobile UI
  package-lock.json
  package.json
  src/app/marketplace/_components/Filter.jsx
  src/app/marketplace/_components/Search.jsx
  src/app/marketplace/_components/Sort.jsx
  src/app/marketplace/page.jsx
  src/assets/icons/ic-close-gray.svg
  src/assets/icons/ic-exchange-gray.svg
  src/components/common/filter.jsx
Labels: Feature, FE

#15 마이갤러리 UI작업중
  src/app/my-gallery/_components/TopSection.jsx
  src/app/my-gallery/page.jsx
Labels: Feature, FE

#16 feat/point 랜덤포인트 기능 구현. 백엔드 연동 및 반응형 추가 필요.
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/jaewook/page.jsx
  src/components/modal/randomPoint/CommonModal.jsx
  src/components/modal/randomPoint/RandomBoxCard.jsx
  src/components/modal/randomPoint/RewardPoint.jsx
  src/components/modal/randomPoint/SurprisePointModal.jsx
  src/hooks/.gitkeep
  src/hooks/useInactiveTimer.js
  src/hooks/usePointRewardTimer.js
  src/utils/.gitkeep
  src/utils/encryption.js
Labels: Feature, FE

#17 fix: 마켓플레이스 상세페이지 디테일 수정
  src/app/marketplace/_components/DetailCard.jsx
  src/app/marketplace/_components/SellerCardInfo.jsx
  src/app/marketplace/sellers/[id]/page.jsx
Labels: FE, UI

#18 feat: 프로필 기능 완성
  src/app/layout.js
  src/components/common/Header.jsx
  src/components/common/HeaderLayout.jsx
  src/components/common/MobileProfileModal.jsx
  src/components/common/TabletAndDesktopProfileModal.jsx
  src/providers/ModalProvider.jsx
Labels: Feature, FE, UI

#22 Feat/market place Responsive CSS
  src/app/marketplace/_components/FilerDropdown.jsx
  src/app/marketplace/_components/Search.jsx
  src/app/marketplace/_components/SortDropdown.jsx
  src/app/marketplace/page.jsx
  src/assets/images/img-marketplace.svg
Labels: FE, UI

#23 feat: Header 분기처리 수정
  src/components/common/HeaderLayout.jsx
Labels: FE, UI

#24 Feat/my gallary
  src/app/my-gallery/_components/Dropdown.jsx
  src/app/my-gallery/_components/PhotoCardSection.jsx
  src/app/my-gallery/_components/RankDiv.jsx
  src/app/my-gallery/_components/RankSection.jsx
  src/app/my-gallery/_components/SortAndSearchSection.jsx
  src/app/my-gallery/_components/TopSection.jsx
  src/app/my-gallery/page.jsx
Labels: FE, Refactor

#26 feat: 마켓플레이스 구매자 UI 1차 구현
  src/app/marketplace/buyers/[id]/_components/MyExchangeOffers.jsx
  src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
  src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx
  src/app/marketplace/buyers/[id]/page.jsx
Labels: FE, UI

#29 fix: 마이갤러리 포토카드 생성 디테일 & 버튼컴포넌트 추가
  src/app/my-gallery/create/page.jsx
  src/components/ui/buttons/ActionButton.jsx
Labels: Feature, FE, UI

#27 feat: 모바일 버전 넓이 수정
  src/app/marketplace/_components/DetailCard.jsx
  src/app/marketplace/_components/Dropdown.jsx
  src/app/marketplace/_components/ExchangeInfo.jsx
  src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
  src/app/marketplace/_components/SellPhotoCardsModal.jsx
  src/app/marketplace/_components/SellPhotoDetail.jsx
  src/app/marketplace/page.jsx
  src/components/common/Card.jsx
  src/components/common/GradeDetail.jsx
  src/utils/GenreChange.js
Labels: Fix, FE, Refactor, UI

#28 feat: Header 레이아웃 수정
  src/components/common/HeaderLayout.jsx
Labels: Fix, FE, UI

#32 fix: 모바일 Header 이미지 크기 수정
  src/components/common/MobileHeader.jsx
Labels: FE, Refactor, UI

#33 feat: 마켓플레이스 구매자 2차 UI 완성
  src/app/marketplace/buyers/[id]/_components/MyExchangeOffers.jsx
  src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
  src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx
  src/app/marketplace/buyers/[id]/page.jsx
Labels: FE, UI

#34 refactor: 구매자 페이지 랭크 리팩터링
  src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
Labels: FE, Refactor, UI

#38 feat: 교환 모달 1차 UI 작업, mobileHeader 위치 수정
  src/app/marketplace/buyers/[id]/_components/ExchangeInputModal.jsx
  src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
  src/app/marketplace/buyers/[id]/_components/SelectExchangePhotoCardModal .jsx
  src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx
  src/app/marketplace/buyers/[id]/page.jsx
  src/components/common/MobileHeader.jsx
Labels: FE, UI

#41 fix: 판매자 상세페이지 & 포토카드 생성페이지 수정
  src/app/marketplace/sellers/[id]/_components/DetailCard.jsx
  src/app/marketplace/sellers/[id]/_components/SellerCardInfo.jsx
  src/app/marketplace/sellers/[id]/page.jsx
  src/app/my-gallery/_components/Dropdown.jsx
  src/app/my-gallery/create/page.jsx
Labels: FE, Refactor

#40 Feat/marketplace sell
  src/api/.gitkeep
  src/api/article.js
  src/api/card.js
  src/api/marketplace.js
  src/app/marketplace/_components/Dropdown.jsx
  src/app/marketplace/_components/ExchangeInfo.jsx
  src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
  src/app/marketplace/_components/SellPhotoCardsModal.jsx
  src/app/marketplace/_components/SellPhotoDetail.jsx
  src/app/marketplace/buyers/[id]/_components/MyExchangeOffers.jsx
  src/app/marketplace/page.jsx
  src/app/marketplace/sellers/[id]/_components/DetailCard.jsx
  src/assets/images/img-marketplace.svg
  src/components/common/Card.jsx
  src/components/common/HeaderLayout.jsx
Labels: Feature, API, FE, UI

#43 Feat/my gallary
  src/app/my-gallery/_components/Dropdown.jsx
  src/app/my-gallery/_components/PhotoCardSection.jsx
  src/app/my-gallery/_components/SortAndSearchSection.jsx
  src/app/my-gallery/_components/TopSection.jsx
  src/app/my-gallery/page.jsx
  src/app/my-sell/_components/PhotoCardSection.jsx
  src/app/my-sell/_components/SortAndSearchSection.jsx
  src/app/my-sell/page.jsx
Labels: Fix, FE

#44 teat/noti 알림 내 스크롤 기능 및 날짜 변환 추가.
  package-lock.json
  package.json
  src/components/modal/notification/Notification.jsx
  src/components/modal/notification/NotificationCard.jsx
  src/components/modal/notification/NotificationsModal.jsx
  src/components/modal/notification/mock_data.json
  src/utils/dateFormat.js
Labels: Feature, FE

#45 마이갤러리 및 나의판매페이지 모바일 필터링 기능 구현중
  src/app/my-gallery/_components/MobileFilter.jsx
  src/app/my-gallery/_components/PhotoCardSection.jsx
  src/app/my-gallery/_components/RankSection.jsx
  src/app/my-gallery/_components/SortAndSearchSection.jsx
  src/app/my-gallery/page.jsx
  src/app/my-sell/_components/MobileFilter.jsx
  src/app/my-sell/_components/PhotoCardSection.jsx
  src/app/my-sell/_components/RankSection.jsx
  src/app/my-sell/_components/SortAndSearchSection.jsx
  src/app/my-sell/page.jsx
  src/providers/ModalProvider.jsx
Labels: Fix, Feature, FE, Refactor

#47 feat:생성페이지 검증
  src/app/my-gallery/create/_components/TopSection.jsx
  src/app/my-gallery/create/page.jsx
Labels: FE

#46 feat: 로그인, 회원가입 관련 api와 util 함수 구현
  src/api/auth.js
  src/app/(auth)/_components/AuthModal.jsx
  src/app/(auth)/_components/AuthSubmitButton.jsx
  src/app/(auth)/_components/FormInput.jsx
  src/app/(auth)/_components/LoginForm.jsx
  src/app/(auth)/_components/PasswordInput.jsx
  src/app/(auth)/_components/SignUpForm.jsx
  src/app/(auth)/_components/SocialAuthOptions.jsx
  src/app/(auth)/login/page.jsx
  src/app/(auth)/signup/page.jsx
  src/app/page.js
  src/hooks/useRedirectIfAuthenticated.js
  src/utils/authValidators.js
Labels: Feature, FE

#48 feat: 마켓플레이스 구매자 교환 모달 2차 UI 완성
  src/app/marketplace/buyers/[id]/_components/ExchangeInputModal.jsx
  src/app/marketplace/buyers/[id]/_components/MyExchangeOffers.jsx
  src/components/common/Desktop.jsx
  src/components/common/Mobile.jsx
  src/components/common/Tablet.jsx
Labels: Feature, FE, UI

#49 Feat/modal provider - 모달프로바이더 모달 위치 지정 가능 (좌측 우측 상단 하단 등)
  src/app/my-sell/_components/SortAndSearchSection.jsx
  src/components/common/HeaderLayout.jsx
  src/components/common/MobileProfileModal.jsx
  src/providers/ModalProvider.jsx
Labels: Feature, FE, Refactor

#50 feat: 구매자 교환 모달 완성
  src/app/marketplace/buyers/[id]/_components/ExchangeInputModal.jsx
  src/providers/ModalProvider.jsx
Labels: Feature, FE, UI

#52 feat: 로그인, 회원가입 페이지 반응형 제작
  src/app/(auth)/_components/AuthLogo.jsx
  src/app/(auth)/_components/AuthModal.jsx
  src/app/(auth)/_components/AuthNavigation.jsx
  src/app/(auth)/_components/AuthSubmitButton.jsx
  src/app/(auth)/_components/FormInput.jsx
  src/app/(auth)/_components/GoogleAuthButton.jsx
  src/app/(auth)/_components/LoginForm.jsx
  src/app/(auth)/_components/PasswordInput.jsx
  src/app/(auth)/_components/SignUpForm.jsx
  src/app/(auth)/_components/SocialAuthOptions.jsx
  src/app/(auth)/login/page.jsx
  src/app/(auth)/signup/page.jsx
  src/assets/icons/ic-google.svg
  src/components/ui/buttons/ActionButton.jsx
  src/hooks/useForm.js
  src/hooks/useLoginForm.js
  src/hooks/useRedirectIfAuthenticated.js
  src/hooks/useSignUpForm.js
Labels: FE, UI

#53 feat: 마켓플레이스 구매자 모달 UI 2차 완성
  src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
  src/app/marketplace/buyers/[id]/_components/SelectExchangePhotoCardModal .jsx
  src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx
  src/app/marketplace/buyers/[id]/_components/modal/BuyPhotoCardModal.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx
Labels: Feature, FE, UI

#56 feat: marketplace 검색과 필터 기능 적용
  src/app/marketplace/_components/Search.jsx
  src/app/marketplace/page.jsx
Labels: Feature, FE

#55 Feat/marketplace sell
  src/api/card.js
  src/app/marketplace/_components/SelectPhotoCardsModal.jsx
  src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
  src/app/marketplace/_components/SellPhotoCardsModal.jsx
  src/app/marketplace/page.jsx
  src/components/common/GradeDetail.jsx
Labels: Fix, Feature, FE, UI

#57 feat: 마켓플레이스 구매자 UI 3차 완성(95%)
  src/app/marketplace/_components/ExchangeCard.jsx
  src/app/marketplace/buyers/[id]/_components/MyExchangeOffers.jsx
  src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
  src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx
  src/app/marketplace/buyers/[id]/_components/modal/BuyPhotoCardModal.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx
Labels: Feature, FE, UI

#59 feat: 마켓플레이스 구매자 자잘한 수정
  src/app/marketplace/_components/ExchangeCard.jsx
  src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
  src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx
  src/app/marketplace/buyers/[id]/_components/modal/BuyPhotoCardModal.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx
Labels: Feature, FE, UI

#63 Feat/marketplace sort 드롭 다운 구현 완료 & 판매 페이지 교환 제시 목록 구현 진행 중
  src/app/marketplace/_components/SortDropdown.jsx
  src/app/marketplace/page.jsx
  src/app/marketplace/sellers/[id]/_components/DetailCard.jsx
  src/app/marketplace/sellers/[id]/_components/ExchangeCards.jsx
  src/app/marketplace/sellers/[id]/page.jsx
Labels: Feature, FE

#62 Feat/my gallary - 마이갤러리 상세페이지 제작 및 랭크 세부 조정
  src/app/my-gallery/[id]/_components/CardInfo.jsx
  src/app/my-gallery/[id]/_components/TopTitle.jsx
  src/app/my-gallery/[id]/page.jsx
  src/app/my-gallery/_components/Dropdown.jsx
  src/app/my-gallery/_components/RankDiv.jsx
  src/app/my-gallery/_components/RankSection.jsx
  src/app/my-gallery/page.jsx
  src/app/my-sell/_components/Dropdown.jsx
  src/app/my-sell/_components/RankDiv.jsx
  src/app/my-sell/_components/RankSection.jsx
  src/app/my-sell/page.jsx
Labels: Feature, FE, UI

#64 Feat/my gallery create img
  src/api/card.js
  src/api/upload.js
  src/app/my-gallery/create/_components/TopSection.jsx
  src/app/my-gallery/create/page.jsx
Labels: FE

#65 feat: 로그인, 회원가입 기능 개발(완료)
  src/api/auth.js
  src/app/(auth)/_components/AuthSubmitButton.jsx
  src/app/(auth)/_components/LoginForm.jsx
  src/app/(auth)/_components/SignUpForm.jsx
  src/lib/fetchClient.js
Labels: Feature, FE

#67 Feat/magallery api
  package-lock.json
  package.json
  src/api/article.js
  src/api/card.js
  src/app/Providers.jsx
  src/app/modal-test/TsetModal.jsx
  src/app/modal-test/page.jsx
  src/app/my-gallery/page.jsx
  src/app/my-sell/page.jsx
  src/providers/QueryProvider.jsx
Labels: Fix, API, FE

#68 feat: 헤더 내 모달 동시동작 제거.
  src/components/common/HeaderLayout.jsx
  src/components/modal/notification/Notification.jsx
Labels: FE, Refactor

#69 Feat/point api 코드 추가 및 연동, useMutaion 으로 리팩토링.
  src/api/point.js
  src/components/modal/randomPoint/RewardPoint.jsx
  src/components/modal/randomPoint/SurprisePointModal.jsx
  src/hooks/useInactiveTimer.js
  src/hooks/useRandomPointTimer.js
Labels: Feature, API, FE, Refactor

#70 Feat/magallery api
  src/app/my-gallery/_components/PhotoCardSection.jsx
  src/app/my-gallery/_components/RankSection.jsx
  src/app/my-gallery/page.jsx
  src/app/my-sell/_components/PhotoCardSection.jsx
  src/app/my-sell/_components/RankSection.jsx
  src/app/my-sell/_components/SortAndSearchSection.jsx
  src/app/my-sell/page.jsx
  src/lib/api/article.api.js
  src/lib/api/card.api.js
Labels: Fix, API, FE

#73 Feat/marketplace 무한스크롤링, 링크 추가
  src/app/marketplace/_components/ExchangeInfo.jsx
  src/app/marketplace/_components/Filter.jsx
  src/app/marketplace/_components/marketplace/ArticleGrid.jsx
  src/app/marketplace/_components/marketplace/Dropdown.jsx
  src/app/marketplace/_components/marketplace/Dropdowns.jsx
  src/app/marketplace/_components/marketplace/MarketplaceHeader.jsx
  src/app/marketplace/_components/marketplace/MobileSortAndFilter.jsx
  src/app/marketplace/_components/marketplace/Search.jsx
  src/app/marketplace/_components/marketplace/SortDropdown.jsx
  src/app/marketplace/_components/marketplace/useMarketplaceArticles.jsx
  src/app/marketplace/page.jsx
  src/lib/api/article.api.js
Labels: Fix, FE, Refactor

#71 Feat/marketplace sell
  src/app/marketplace/_components/SelectPhotoCardsModal.jsx
  src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
  src/lib/api/article.api.js
  src/lib/api/card.api.js
Labels: Feature, API, UI

#76 Feat/marketplace chore
  src/app/marketplace/_components/marketplace/ArticleGrid.jsx
  src/app/marketplace/_components/marketplace/LoginNeed.jsx
  src/app/marketplace/page.jsx
  src/lib/api/article.api.js
Labels: Fix, Feature, FE

#75 Fix/create card api
  src/app/my-gallery/create/page.jsx
  src/lib/api/card.api.js
Labels: API, FE, Refactor

#79 Feat/loading / 로딩 스피너 구현 + 버셀 배포오류 수정
  src/app/my-gallery/_components/Dropdown.jsx
  src/app/my-gallery/_components/Loading.jsx
  src/app/my-gallery/_components/MyGallery.jsx
  src/app/my-gallery/_components/SortAndSearchSection.jsx
  src/app/my-gallery/page.jsx
  src/app/my-sell/_components/Dropdown.jsx
  src/app/my-sell/_components/MobileFilter.jsx
  src/app/my-sell/_components/MySell.jsx
  src/app/my-sell/_components/PhotoCardSection.jsx
  src/app/my-sell/_components/SortAndSearchSection.jsx
  src/app/my-sell/page.jsx
  src/lib/api/article.api.js
  src/lib/api/card.api.js
Labels: Fix, Feature, FE

#81 feat/point 포인트 내에서 auth 관련 코드 추가.
  src/components/modal/randomPoint/RewardPoint.jsx
  src/components/modal/randomPoint/SurprisePointModal.jsx
Labels: FE, Refactor, UI

#82 Feat/marketplace chore
  src/app/marketplace/_components/marketplace/ArticleGrid.jsx
  src/app/marketplace/_components/marketplace/LoginNeed.jsx
  src/app/marketplace/_components/marketplace/MarketplaceHeader.jsx
  src/app/marketplace/_components/marketplace/MyCardSellBtn.jsx
  src/app/marketplace/page.jsx
  src/lib/api/article.api.js
Labels: Feature, API, FE

#80 feat: 마켓플레이스 API 연동
  src/app/marketplace/_components/ExchangeCard.jsx
  src/app/marketplace/_components/SelectPhotoCardsModal.jsx
  src/app/marketplace/buyers/[id]/_components/MyExchangeOffer.jsx
  src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
  src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx
  src/app/marketplace/buyers/[id]/_components/modal/BuyPhotoCardModal.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx
  src/app/marketplace/buyers/[id]/page.jsx
  src/lib/api/article.api.js
Labels: Feature, API, FE

#87 feat: 마켓플레이스 구매자 API 연동 관련해서 작은 수정
  src/app/marketplace/_components/ExchangeCard.jsx
  src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
  src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx
  src/lib/api/article.api.js
Labels: Feature, API, FE

#88 feat: 헤더 레이아웃, 유저 프로파일 모달에 AuthProvider로 전역 유저정보 적용
  src/components/common/HeaderLayout.jsx
  src/components/common/MobileProfileModal.jsx
  src/components/common/TabletAndDesktopProfileModal.jsx
  src/lib/api/fetchClient.api.js
Labels: FE, Refactor, UI

#93 fix: 프로필 모달 화면 크기에 따라서 자동으로 닫히도록 수정
  src/components/common/HeaderLayout.jsx
  src/components/common/MobileProfileModal.jsx
  src/components/common/TabletAndDesktopProfileModal.jsx
Labels: Fix, FE
