Repository De-cal/6-Favorite_Photo-FE, pull requests merged in 2025-06, with the labels that each got.

#94 fix: marketplace 인가 오류 수정
  src/app/marketplace/_components/marketplace/ArticleGrid.jsx
  src/app/marketplace/_components/marketplace/MarketplaceHeader.jsx
  src/app/marketplace/_components/marketplace/MyCardSellBtn.jsx
  src/lib/api/article.api.js
Labels: Fix, FE

#95 fix:QA테스트 결과 부분반영
  src/app/marketplace/page.jsx
  src/app/modal-test/page.jsx
  src/app/my-gallery/_components/MyGallery.jsx
  src/app/my-gallery/_components/PageNation.jsx
  src/app/my-gallery/_components/PhotoCardSection.jsx
  src/app/my-gallery/page.jsx
  src/app/my-sell/_components/MobileFilter.jsx
  src/app/my-sell/_components/MySell.jsx
  src/app/my-sell/_components/PageNation.jsx
  src/app/my-sell/_components/PhotoCardSection.jsx
  src/app/my-sell/page.jsx
  src/assets/icons/ic-alert.svg
Labels: Fix, FE, UI

#97 Feat/marketplace sell
  src/app/globals.css
  src/app/marketplace/_components/ExchangeInfo.jsx
  src/app/marketplace/_components/SelectPhotoCardsModal.jsx
  src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
  src/app/marketplace/_components/SellPhotoDetail.jsx
  src/app/marketplace/_components/marketplace/Dropdown.jsx
Labels: Fix, UI

#96 refactor: 객체 구조분해 간소화
  src/app/marketplace/_components/ExchangeCard.jsx
  src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx
  src/lib/api/article.api.js
Labels: Feature, FE, Refactor, UI

#98 Feat/marketplace exchange
  src/app/marketplace/_components/marketplace/ArticleGrid.jsx
  src/app/marketplace/sellers/[id]/_components/ExchangeCards.jsx
  src/app/marketplace/sellers/[id]/page.jsx
  src/lib/api/article.api.js
Labels: API, FE

#100 feat: 구매자 상세 페이지 교환 목록 불러오기 구현
  next.config.mjs
  src/app/marketplace/_components/ExchangeCard.jsx
  src/app/marketplace/buyers/[id]/_components/MyExchangeOffer.jsx
  src/app/marketplace/sellers/[id]/page.jsx
  src/lib/api/article.api.js
Labels: Feature, FE, UI

#102 Feat/marketplace sell
  src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
  src/app/marketplace/sellers/[id]/_components/SellerCardInfo.jsx
  src/app/my-sell/_components/PhotoCardSection.jsx
  src/lib/api/article.api.js
Labels: Feature, API

#110 feat: 로그인 회원가입, 헤더레이아웃 QA 피드백 반영
  src/app/(auth)/_components/AuthModal.jsx
  src/app/(auth)/_components/FormInput.jsx
  src/app/(auth)/_components/PasswordInput.jsx
  src/app/(auth)/login/page.jsx
  src/app/(auth)/signup/page.jsx
  src/components/common/HeaderLayout.jsx
  src/components/common/MobileProfileModal.jsx
  src/lib/api/fetchClient.api.js
  src/lib/utils/authValidators.js
Labels: Fix, Feature, FE, Refactor

#113 refactor: AuthProvider에 isLoading 상태값 추가, HeaderLayout에 적용
  src/components/common/HeaderLayout.jsx
  src/providers/AuthProvider.jsx
Labels: FE, UI

#111 Feat/skeleton add at makeyt
  src/app/marketplace/_components/marketplace/ArticleGrid.jsx
  src/app/marketplace/page.jsx
  src/app/my-gallery/_components/MyGallery.jsx
  src/app/my-gallery/_components/RankSection.jsx
  src/app/my-gallery/create/page.jsx
  src/app/my-sell/_components/CardSkeleton.jsx
  src/app/my-sell/_components/MobileFilter.jsx
  src/app/my-sell/_components/MySell.jsx
  src/app/my-sell/_components/PhotoCardSection.jsx
  src/app/my-sell/_components/RankSection.jsx
  src/lib/api/card.api.js
Labels: Feature, FE, UI

#118 Feat/noti 알림 기능 내 무한 스크롤 구현 및 QA 피드백 적용.
  src/components/modal/notification/Notification.jsx
  src/components/modal/notification/NotificationCard.jsx
  src/components/modal/notification/NotificationsModal.jsx
  src/components/modal/notification/NotificationsModalMobile.jsx
  src/lib/api/notification.api.js
Labels: Fix, Feature, FE, Refactor, UI

#121 Fix/detail
  next.config.mjs
  package-lock.json
  package.json
  src/app/marketplace/[id]/seller/_components/DeletePhotoCardModal.jsx
  src/app/marketplace/[id]/seller/_components/SellerCardInfo.jsx
  src/app/marketplace/[id]/seller/page.jsx
  src/app/my-gallery/create/_components/TopSection.jsx
  src/app/my-gallery/create/page.jsx
  src/components/common/Card.jsx
  src/lib/api/card.api.js
  src/lib/utils/imageUrl.js
  src/providers/AuthProvider.jsx
Labels: Feature, FE, UI

#122 fix: 랜딩페이지 반응형 개선 & Next middleware 로직 수정
  src/app/_components/LandingFeatFirst.jsx
  src/app/_components/LandingFeatSecond.jsx
  src/app/_components/LandingFeatThird.jsx
  src/app/_components/LandingHero.jsx
  src/app/page.js
  src/middleware.js
Labels: Fix, Feature, Refactor

#126 Fix: 이미지 연결 안된 페이지 연동
  src/app/marketplace/[id]/seller/_components/DetailCard.jsx
  src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
  src/app/marketplace/_components/marketplace/ArticleGrid.jsx
  src/components/common/Card.jsx
Labels: Fix, FE, UI

#128 chore: next.config.js 수정
  next.config.mjs
Labels: Chore

#129 chore: middleware 주석처리
  src/app/_components/LandingHero.jsx
  src/middleware.js
Labels: Fix

#131 chore: 미들웨어 버셀에서 안쓰도록 파일명 변경
  src/middleware.temp.js
Labels: Chore

#132 fix: 컨텍스트 API 프로바이더 바인딩 수정
  src/app/layout.js
  src/app/marketplace/[id]/buyer/page.jsx
Labels: Fix, FE, Refactor

#134 Fix/detail
  src/app/marketplace/[id]/seller/page.jsx
  src/app/marketplace/_components/ExchangeCard.jsx
  src/lib/api/notification.api.js
Labels: Fix, Feature, FE

#138 fix/모바일필터 조정
  src/app/my-sell/_components/MobileFilter.jsx
  src/app/my-sell/_components/MySell.jsx
  src/providers/ModalProvider.jsx
Labels: Fix, Feature

#141 feat: imgUrl 수정
  src/app/marketplace/[id]/buyer/_components/PhotoCardBuyerDetail.jsx
Labels: Fix, Feature, FE, Refactor

#144 fix: getUser로 모달 닫히는 현상 디버그
  src/app/marketplace/[id]/buyer/_components/modal/BuyPhotoCardModal.jsx
  src/components/common/CommonModal.jsx
Labels: Fix, FE

#145 Feat/marketplace sort 간격 조정
  src/app/marketplace/_components/marketplace/SortDropdown.jsx
Labels: FE, UI

#146 fix: 이미지 수정
  src/app/marketplace/[id]/seller/_components/SellerCardInfo.jsx
  src/app/marketplace/[id]/seller/page.jsx
Labels: Fix

#153 Fix/exprot default fnuc
  src/app/marketplace/[id]/seller/_components/DetailCard.jsx
  src/app/marketplace/_components/ExchangeInfo.jsx
  src/app/marketplace/_components/SelectPhotoCardsModal.jsx
  src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
  src/app/marketplace/_components/SellPhotoDetail.jsx
  src/app/marketplace/_components/marketplace/Dropdown.jsx
  src/app/marketplace/_components/marketplace/Search.jsx
  src/app/marketplace/_components/marketplace/useMarketplaceArticles.jsx
  src/app/my-gallery/[id]/_components/CardInfo.jsx
  src/app/my-gallery/[id]/_components/TopTitle.jsx
  src/app/my-gallery/[id]/page.jsx
  src/app/my-gallery/_components/SortAndSearchSectionSkeleton.jsx
  src/app/my-gallery/_components/tttt.jsx
  src/app/my-sell/_components/CardSkeleton.jsx
  src/app/my-sell/_components/PageNationSkeleton.jsx
  src/app/my-sell/_components/PhotoCardSection.jsx
  src/app/my-sell/_components/SortAndSearchSectionSkeleton.jsx
  src/app/my-sell/_components/TopSection.jsx
  src/components/common/Card.jsx
  src/components/common/CommonModal.jsx
  src/components/common/filter.jsx
  src/components/modal/notification/NotificationCard.jsx
  src/components/modal/notification/NotificationsModal.jsx
  src/components/modal/notification/NotificationsModalMobile.jsx
  src/components/modal/randomPoint/RandomBoxCard.jsx
  src/components/modal/randomPoint/RewardPoint.jsx
  src/components/modal/randomPoint/SurprisePointModal.jsx
  src/hooks/useInactiveTimer.js
  src/hooks/useRandomPointTimer.js
Labels: Chore, FE, Refactor

#154 Chore/cleanup 안쓰는 코드 정리 및 컨벤션에 맞게 api코드 수정.
  src/app/jaewook/page.jsx
  src/app/marketplace/[id]/_components/ExchangeModal.jsx
  src/app/marketplace/[id]/buyer/_components/modal/BuyPhotoCardModal.jsx
  src/app/marketplace/[id]/buyer/_components/modal/ExchangeInputModal.jsx
  src/app/modal-test/TsetModal.jsx
  src/app/modal-test/page.jsx
  src/app/page.js
  src/contexts/BuyerContext.js
  src/lib/api/article.api.js
  src/lib/api/auth.api.js
  src/lib/api/card.api.js
  src/lib/api/fetchClient.api.js
  src/lib/api/notification.api.js
  src/lib/api/upload.api.js
  src/providers/AuthProvider.jsx
Labels: FE, Refactor

#155 Feat/marketplace
  src/app/marketplace/_components/marketplace/SortDropdown.jsx
Labels: Fix, FE, UI
